#!/bin/sh
dte(){
        dte="$(date +"%a,%b-%d-%y|%R")"
        echo "$dte"
}

hdd(){
        hdd="$(df -h /home | grep dev | awk '{print$3"="$5}')"
        echo "HDD:$hdd"
}

mem(){
        mem="$(free -h | awk '/Mem:/ {printf $3 "/" $2}')"
        echo "Mem:$mem"
}

temp(){
	mytemp="$(cat /sys/class/thermal/thermal_zone0/temp)"
	temp=$(($mytemp/1000))
	echo "$temp℃"
}

cpu() {
    read cpu a b c previdle rest < /proc/stat
      prevtotal=$((a+b+c+previdle))
        sleep 0.5
          read cpu a b c idle rest < /proc/stat
            total=$((a+b+c+idle))
              cpu=$((100*( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal) ))
                echo "CPU:$cpu%,"
}

vol(){
	vol="$(amixer get Master | awk -F'[][]' 'END{print ":"$2}')"
	echo "Volume$vol"
}

bat() {
	battery="$(cat /sys/class/power_supply/BAT0/capacity)"
	echo "$battery%"
}

batstat() {
	bstat="$(cat /sys/class/power_supply/BAT0/status)"
	echo "$bstat"
}

status(){
	echo "|$(cpu)$(temp)|$(mem)|$(hdd)|$(bat):$(batstat)|$(vol)|$(dte)|"
}


while true; do
	xsetroot -name "$(status)"
	sleep 1
done
