#!/bin/sh

dte(){
	dte="$(date +"%a,%b-%d-%y|%R")"
	echo "$dte"
}

temp(){
	get_temp_cpu0=$(cat /sys/class/thermal/thermal_zone0/temp)
	temp_cpu0=$(($get_temp_cpu0/1000))
	echo "" $temp_cpu0"°C"
}

cpu() {
    read cpu a b c previdle rest < /proc/stat
      prevtotal=$((a+b+c+previdle))
        sleep 0.5
          read cpu a b c idle rest < /proc/stat
            total=$((a+b+c+idle))
              cpu=$((100*( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal) ))
                echo ":$cpu%,"
}

mem(){
	mem_total=$(free -m | awk 'NR%2==0 {print $2}')
	mem_avail=$(free -m | awk 'NR%2==0 {print $7}')
	mem_used=$(( $mem_total - $mem_avail))
	mem_usage=$(( $mem_used * 100 / $mem_total ))
	echo " "$mem_usage"%"
}

hdd(){
	cap_percentage=$(df -h --output=pcent / | awk 'NR%2==0 {print $0}')
	echo ""$cap_percentage
}

vol(){
	ou_mute=$(pamixer --get-mute)
	in_mute=$(pamixer --source 1 --get-mute)
	ou_vol=$(pamixer --get-volume)
	in_vol=$(pamixer --source 1 --get-volume)
	jack_stat=$($HOME/.local/bin/has_headphone)

	if   [ $jack_stat = "yes" ]; then
    	icon_ou_on=""
	    icon_ou_off=""
	elif [ $jack_stat = "no"  ]; then
    	icon_ou_on=""
	    icon_ou_off=""
	fi
	icon_in_on=""
	icon_in_off=""

	if   [ $ou_mute = "true"  ] && [ $in_mute = "true"  ]; then
    	echo $icon_ou_off "Ø" $icon_in_off "Ø"
	elif [ $ou_mute = "true"  ] && [ $in_mute = "false" ]; then
    	echo $icon_ou_off "Ø" $icon_in_on $in_vol"%"
	elif [ $ou_mute = "false" ] && [ $in_mute = "true"  ]; then
    	echo $icon_ou_on $ou_vol"%" $icon_in_off "Ø"
	elif [ $ou_mute = "false" ] && [ $in_mute = "false" ]; then
    	echo $icon_ou_on $ou_vol"% $icon_in_on $in_vol"%"
	else
    	echo " ERROR
	fi
}

backlight(){
	backlight=$(xbacklight -get | cut -d "." -f1)
	echo "" $backlight"%"
}

bat(){
	cap=$(cat /sys/devices/platform/smapi/BAT0/remaining_percent)
	if   [ $cap -ge 0  ] && [ $cap -le 10  ]; then
    	echo "" $cap"%"
	elif [ $cap -ge 11 ] && [ $cap -le 20  ]; then
    	echo "" $cap"%"
	elif [ $cap -ge 21 ] && [ $cap -le 30  ]; then
    	echo "" $cap"%"
	elif [ $cap -ge 31 ] && [ $cap -le 40  ]; then
    	echo "" $cap"%"
	elif [ $cap -ge 41 ] && [ $cap -le 50  ]; then
    	echo "" $cap"%"
	elif [ $cap -ge 51 ] && [ $cap -le 60  ]; then
    	echo "" $cap"%"
	elif [ $cap -ge 61 ] && [ $cap -le 70  ]; then
    	echo "" $cap"%"
	elif [ $cap -ge 71 ] && [ $cap -le 80  ]; then
    	echo "" $cap"%"
	elif [ $cap -ge 81 ] && [ $cap -le 90  ]; then
    	echo "" $cap"%"
	elif [ $cap -ge 91 ] && [ $cap -le 100 ]; then
    	echo "" $cap"%"
	else
    	echo " UNKNWN"
	fi
}

batstat(){
	state=$(cat /sys/devices/platform/smapi/BAT0/state)
	if   [ $state = "charging"    ]; then
	    echo " " # charging
	elif [ $state = "discharging" ]; then
	    echo " " # discharging
	elif [ $state = "idle"        ]; then
	    echo " " # idle
	else
    	echo " " # unknown
	fi
}

status(){
	echo "|$(temp)$(cpu)|$(mem)|$(hdd)|$(bat)$(batstat)|$(vol)|$(dte)|"
}

while true; do 
	xsetroot -name "$(status)"
	sleep 1
done
