# statusbar
~/.other/.script/dwmbar &

# wallpaper
feh --bg-fill ~/Pictures/015.png &

# enable pop-up notification
dunst -config ~/.config/dunst/dunstrc &

# notification for battery system
~/.other/.script/battery-notification &

# disable screen tearing
picom --experimental-backend --no-fading-openclose --menu-opacity 1 &

# start dwm
exec dwm
